### ISSUE TITLE
Add snap client?

### ISSUE THREAD

**Issue by zyrolasting** [Bogdanp/racksnaps#3]
@Bogdanp I went ahead and started an [`add-snap-client`](https://github.com/Bogdanp/racksnaps/tree/add-snap-client) branch. It makes a couple of assumptions that I need to run by you.

The big assumption being that `racksnaps` is itself suitable for publication on a catalog, such that if a user installs it, it's for the sake of a `raco snap` client. Obviously this is independent of containerization and is at the mercy of the default catalog.

I already put in a bare-bones command that writes a `config.rktd` with the endpoint you put up, but I figure there's room to grow and make a suite of cool commands. That's the second assumption.

Is fleshing out a client worth it? If so, are you okay with me writing client-side code in this way, or would you rather I put it in a different repository?

**Comment by Bogdanp** [comment]
I think a client to help manage catalogs like this would be hugely beneficial, but it should probably live in a separate repo so we don't ship racksnaps itself to users.

**Comment by zyrolasting** [comment]
Alright, I'll scoot everything over. Thanks much.
